spring.application.name=sb-ecom

# H2 Database connection
#spring.h2.console.enabled = true
#spring.datasource.url = jdbc:h2:mem:test
#spring.jpa.show-sql = true
#spring.jpa.properties.hibernate.format_sql = true
#spring.jpa.hibernate.ddl-auto = create-drop

project.image = images/

spring.app.jwtSecret =mySecretKey123912738vtyfuy35dxszdc56t7t6y87y8cvdxcsezxfcrf454rtrc
spring.app.jwtExpirationMs =300000000

spring.ecom.app.jwtCookie =springBootEcom

#to show more logs
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG

#Postgres Database Connection local
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
#spring.datasource.username=postgres
#spring.datasource.password=Perekeme123??

#Postgres Database Connection render
spring.datasource.url=jdbc:postgresql://peresko_user:wZ6s6dcJDf9gjpv3S69hw809TLBEDWij@dpg-d5p10p4oud1c739ibtag-a/peresko
spring.datasource.username=peresko_user
spring.datasource.password=wZ6s6dcJDf9gjpv3S69hw809TLBEDWij

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect